### ISSUE TITLE
Can we use translate in the typescript class?

### ISSUE THREAD

**Issue by chr1soscl** [ngx-translate/example#5]
Is it possible to use translate in the typescript side? I am injecting some labels dynamically to other components, is there a way to pull the label with translate?

**Comment by JhernandezZ** [comment]
Yes, you can.

You can inject the `TranslateService` in the constructor, then you can get the translation that you need.

```typescript
export class AppComponent {

    constructor(translate: TranslateService) {
        translate.get('HELLO', {value: 'world'}).subscribe((res: string) => {
            console.log(res);
            //=> 'hello world'
            // here goes the logic that you need/want in order to make the label
        });
    }
}
```

**Comment by chr1soscl** [comment]
I found a way to do it, I inject a TranslateService to the component:
<pre><code>
constructor(private translate: TranslateService) { }
</pre></code>
and then I get the text this way in the typescript side:
<pre><code>
this.translate.instant('Navigationpage.search')
</pre></code>
